services:
  beaverdam:
    build:
      context: .
      dockerfile: Dockerfile
    image: beaverdam:latest
    container_name: beaverdam
    restart: unless-stopped
    mem_limit: 4g
    env_file:
      - .env
    depends_on:
      - beaverdam-db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./beaverdam-data:/data
    environment:
      TZ: "Europe/Warsaw"
#      SPRING_PROFILES_ACTIVE: "prod"
    ports:
      - "${HOST_MACHINE}:8081:8080"
#    networks:
#      - default
#      - vpn-connection

  beaverdam-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: beaverdam-frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_MACHINE}:3000:3000"
    environment:
      BACKEND_URL: "http://beaverdam:8080"
      TZ: "Europe/Warsaw"
    depends_on:
      - beaverdam


  beaverdam-db:
    image: 'postgres:latest'
    container_name: "beaverdam-db"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./beaverdam-data/postgres-db:/var/lib/postgresql
    ports:
      - "${HOST_MACHINE}:5434:5432"

  beaverdam-cloudflared:
    image: 'cloudflare/cloudflared:latest'
    container_name: "beaverdam-cloudflared"
    restart: unless-stopped
    command: tunnel run
    environment:
      TZ: "Europe/Warsaw"
      TUNNEL_TOKEN: ${CF_TUNNEL_TOKEN}
      TUNNEL_LOGLEVEL: "info"



networks:
  vpn-connection:
    external: true
    driver: bridge
    name: vpn-connection