spring.config.import=optional:file:.env[.properties]

spring.application.name=BeaverDam
spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://${DB_ADDRESS}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.default-schema=public
spring.flyway.schemas=public,watchpost,discord

watchpost.vpn.enabled=${VPN_ENABLED:true}
watchpost.vpn.host=${VPN_HOST:localhost}
watchpost.vpn.port=${VPN_PORT:8888}
watchpost.showseries.poll_interval=1800000
watchpost.showseries.default_share_ratio=2.0

discord.bot.token=${DISCORD_BOT_TOKEN}
discord.bot.owner_id=${DISCORD_BOT_OWNER_ID}
discord.bot.main_guild_id=${DISCORD_BOT_MAIN_GUILD_ID}
discord.alert.anime.control_panel_channel=${DISCORD_CONTROL_PANEL_CHANNEL_ID}
discord.alert.anime.interesting_anime_channel=${DISCORD_INTERESTING_ANIME_CHANNEL_ID}
discord.alert.anime.silent_channel=${DISCORD_SILENT_ANIME_CHANNEL_ID}
discord.alert.log_channel=${DISCORD_LOG_CHANNEL_ID}