CREATE SCHEMA IF NOT EXISTS "watchpost";

CREATE SCHEMA IF NOT EXISTS "discord";

CREATE TABLE "watchpost"."anime_rss_items" (
                                               "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               "rss_feed_id" bigint,
                                               "show_series_id" bigint,
                                               "internal_file_id" bigint,
                                               "raw_item_name" varchar(1000),
                                               "series_name" varchar(1000),
                                               "localized_name" varchar(1000),
                                               "group_name" varchar(255),
                                               "episode" varchar(255),
                                               "season" varchar(255),
                                               "release_season" varchar(255),
                                               "rss_category" varchar(255),
                                               "video_category" varchar(255),
                                               "file_link" varchar(1200),
                                               "file_size" bigint,
                                               "guid" varchar(255),
                                               "online_id" varchar(255),
                                               "pub_date" timestamp,
                                               "local_save_date" timestamp,
                                               "info_hash" varchar(255) UNIQUE NOT NULL,
                                               "downloaded" boolean,
                                               "displayed" boolean,
                                               "repack" boolean
);

CREATE TABLE "watchpost"."video_details" (
                                             "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             "anime_rss_item_id" bigint UNIQUE,
                                             "resolution" varchar(255),
                                             "source" varchar(255),
                                             "source_type" varchar(255),
                                             "video_type" varchar(255),
                                             "audio_type" varchar(255),
                                             "subtitles" varchar(500),
                                             "crc32_checksum" varchar(255)
);

CREATE TABLE "watchpost"."rss_feeds" (
                                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "rss_reader_name" varchar(255),
                                         "feed_name" varchar(255),
                                         "feed_url" varchar(1000),
                                         "poll_interval" bigint,
                                         "enabled" boolean,
                                         "last_successful_fetch" timestamp,
                                         "last_error_message" varchar(1000)
);

CREATE TABLE "watchpost"."show_series" (
                                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           "series_name" varchar(255),
                                           "online_id" bigint UNIQUE,
                                           "mal_link" varchar(1000),
                                           "release_season" varchar(255),
                                           "is_interesting" boolean,
                                           "is_ignored" boolean,
                                           "auto_download" boolean,
                                           "submitted" boolean,
                                           "custom_share_ratio" varchar(255),
                                           "last_seen" timestamp,
                                           "added_on" timestamp
);

CREATE TABLE "discord"."ui_messages" (
                                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "discord_message_id" bigint,
                                         "discord_channel_id" bigint,
                                         "target_module" varchar(255),
                                         "target_item_id" bigint
);

CREATE INDEX "idx_ari_rss_feed_id" ON "watchpost"."anime_rss_items" ("rss_feed_id");

CREATE INDEX "idx_ari_show_series_id" ON "watchpost"."anime_rss_items" ("show_series_id");

CREATE INDEX "idx_ari_series_name" ON "watchpost"."anime_rss_items" ("series_name");

CREATE INDEX "idx_ari_pub_date" ON "watchpost"."anime_rss_items" ("pub_date");

CREATE INDEX "idx_ss_series_name" ON "watchpost"."show_series" ("series_name");

CREATE INDEX "idx_ss_online_id" ON "watchpost"."show_series" ("online_id");

CREATE INDEX "idx_um_id" ON "discord"."ui_messages" ("id");

CREATE INDEX "idx_um_target_item_id" ON "discord"."ui_messages" ("target_item_id");

COMMENT ON COLUMN "watchpost"."anime_rss_items"."internal_file_id" IS 'A future consideration, It will allow me to track the file via a separate table, for example to check if I have watched it already etc, to move it to a correct directory in storage';

COMMENT ON COLUMN "watchpost"."anime_rss_items"."episode" IS 'Sometime can be "Movie" or "ONA" or even different combinations that can be quite long, so just to be save';

COMMENT ON COLUMN "watchpost"."anime_rss_items"."release_season" IS 'For ex: Winter 2025, Spring 2026';

COMMENT ON COLUMN "watchpost"."show_series"."custom_share_ratio" IS 'qbit wants it in string/byte form so it doesnt matter, and it being a string allows me to make it, none or infinite, etc';

ALTER TABLE "watchpost"."anime_rss_items" ADD FOREIGN KEY ("rss_feed_id") REFERENCES "watchpost"."rss_feeds" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "watchpost"."anime_rss_items" ADD FOREIGN KEY ("show_series_id") REFERENCES "watchpost"."show_series" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "watchpost"."video_details" ADD FOREIGN KEY ("anime_rss_item_id") REFERENCES "watchpost"."anime_rss_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;
