CREATE SCHEMA IF NOT EXISTS "analytics";

CREATE TABLE "analytics"."discord_voice_states"
(
    "id"                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "guild_id"            bigint       not null,
    "user_id"             bigint       not null,
    "username"            varchar(100) not null,
    "timestamp"           timestamp    not null,
    "event_type"          varchar(50)  not null,
    "action_trigger"      varchar(50)  not null,
    "channel_id"          bigint,
    "previous_channel_id" bigint,
    "state_value"         boolean
);

CREATE TABLE "analytics"."discord_voice_sessions"
(
    "id"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "guild_id" bigint       not null,
    "user_id"  bigint       not null,
    "username" varchar(100) not null,
    "channel_id"          bigint not null,
    "joined_at" timestamp not null,
    "left_at" timestamp not null,
    "duration_seconds" bigint not null
);

CREATE INDEX idx_voice_states_user_id ON analytics.discord_voice_states (user_id);
CREATE INDEX idx_voice_states_guild_id ON analytics.discord_voice_states (guild_id);
CREATE INDEX idx_voice_states_timestamp ON analytics.discord_voice_states (timestamp);
CREATE INDEX idx_voice_sessions_user_id ON analytics.discord_voice_sessions (user_id);
CREATE INDEX idx_voice_sessions_guild_id ON analytics.discord_voice_sessions (guild_id);
CREATE INDEX idx_voice_sessions_timestamp ON analytics.discord_voice_sessions (joined_at);