CREATE SCHEMA IF NOT EXISTS "watchpost";

CREATE TABLE "watchpost"."show_metadata"
(
    "id"              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "show_series_id"  bigint    not null unique,
    "mal_id"          bigint,
    "anilist_id"      bigint,
    "localized_name"  varchar(1000),
    "cover_image_url" varchar(1000),
    "synopsis"        TEXT,
    "genres"          varchar(255),
    "status"          varchar(255),
    last_updated      timestamp not null default CURRENT_TIMESTAMP,
    constraint fk_show_metadata_series foreign key (show_series_id) references watchpost.show_series (id) on delete cascade
);

create INDEX idx_show_metadata_series_id on watchpost.show_metadata(show_series_id);